---
title: "Data files"
author: "Daniel Antal, CFA"
date: "2/19/2021"
output:
  md_document: default
  html_document: default
bibliography: sustainability.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

In our [tutorial series](http://netzero.dataobservatory.eu/post/2021-03-04_retroharmonize_intro/), we are going to harmonize the following questionnaire items from five Eurobarometer harmonized survey files. The Eurobarometer survey files are harmonized across countries, but they are only partially harmonized in time.

All data must be downloaded from the [GESIS](https://www.gesis.org/en/home) Data Archive in Cologne. We are not affiliated with GESIS and you must read and accept their terms to use the data.

## Eurobarometer 80.2 (2013)

GESIS Data Archive, Cologne. ZA5877 Data file Version 2.0.0, https://doi.org/10.4232/1.12792


* Data file: [ZA6595](https://search.gesis.org/research_data/ZA5877) data file [@ZA5877].
* Questionnaire: [Eurobarometer 83.4 Basic Bilingual Questionnaire](https://dbk.gesis.org/dbksearch/download.asp?id=54036)
* Citation: [ZA6595 Bibtex](https://search.gesis.org/ajax/bibtex.php?type=research_data&docid=ZA5877&lang=en)

`QA1a Which of the following do you consider to be the single most serious problem facing the world as a whole?` (single choice)

`QA1b Which others do you consider to be serious problems?` (multiple choice)

`QA2 And how serious a problem do you think climate change is at this moment? Please use a scale from 1 to 10, with '1' meaning it is "not at all a serious problem"` (scale 1-10)

`QA4 To what extent do you agree or disagree with each of the following statements? - Fighting climate change and using energy more efficiently can boost the economy and jobs in the EU` (agreement-disagreement 4-scale)

`QA4 To what extent do you agree or disagree with each of the following statements? - Reducing fossil fuel imports from outside the EU could benefit the EU economically` (agreement-disagreement 4-scale)

`QA5 Have	you	personally taken any action to fight climate change over the past six months?` (binary)

## Eurobarometer 83.4 (2015)

European Commission, Brussels; Directorate General Communication COMM.A.1 ´Strategy, Corporate Communication Actions and Eurobarometer´GESIS Data Archive, Cologne. ZA6595 Data file Version 3.0.0, https://doi.org/10.4232/1.13146

* Data file: [ZA6595](https://search.gesis.org/research_data/ZA6595) data file [@ZA6595].
* Questionnaire: [Eurobarometer 83.4 Basic Bilingual Questionnaire](https://dbk.gesis.org/dbksearch/download.asp?id=57940)
* Citation: [ZA6595 Bibtex](https://search.gesis.org/ajax/bibtex.php?type=research_data&docid=ZA6595&lang=en)


## Eurobarometer 87.1 (2017)
European Commission, Brussels; Directorate General Communication, COMM.A.1 ‘Strategic Communication’; European Parliament, Directorate-General for Communication, Public Opinion Monitoring Unit
GESIS Data Archive, Cologne. ZA6861 Data file Version 1.2.0, https://doi.org/10.4232/1.12922

* Data file: [ZA6861](https://search.gesis.org/research_data/ZA6861) data file.
* Questionnaire: [Eurobarometer 90.2 Basic Bilingual Questionnaire](https://dbk.gesis.org/dbksearch/download.asp?id=65967)
* Citation: [ZA6861 Bibtex](https://search.gesis.org/ajax/bibtex.php?type=research_data&docid=ZA6861&lang=en)


`QC1a Which of the following do you consider to be the single most serious problem facing the world as a whole?` (single choice)

`QC1b Which others do you consider to be serious problems?` (multiple choice)

`QC2 And how serious a problem do you think climate change is at this moment? Please use a scale from 1 to 10, with '1' meaning it is "not at all a serious problem"` (scale 1-10)

`Qc4 To what extent do you agree or disagree with each of the following statements? - Fighting	climate	change	and	using	energy	more	efficiently	can	boost	the	economy	and	jobs in	the	EU` (agreement-disagreement 4-scale)

`Qc4 To what extent do you agree or disagree with each of the following statements? - Promoting	EU	expertise	in	new	clean	technologies	to countries	outside	the	EU can	benefit	the	EU economically`	(agreement-disagreement 4-scale)

`Qc4 To what extent do you agree or disagree with each of the following statements? - Reducing	fossil	fuel	imports	from outside	the	EU can benefit the EU economically` (agreement-disagreement 4-scale)

`Qc4 To what extent do you agree or disagree with each of the following statements? - Reducing fossil fuel imports from outside the	EU can increase the security of EU energy supplies` (agreement-disagreement 4-scale)

`Qc4 To what extent do you agree or disagree with each of the following statements? - More public financial support should be given	to the transition to clean energies	even if it means subsidies to	fossil fuels should	be reduced.` (agreement-disagreement 4-scale)

`Qc5 Have	you	personally taken any action to fight climate change over the past six months?` (binary)


## Eurobarometer 90.2 (2018)

European Commission, Brussels; Directorate General Communication, COMM.A.3 ‘Media Monitoring and Eurobarometer’
GESIS Data Archive, Cologne. ZA7488 Data file Version 1.0.0, https://doi.org/10.4232/1.13289

* Data file: [ZA7488](https://dbk.gesis.org/dbksearch/sdesc2.asp?db=e&no=7488) data file  [@ZA7488]
* Questionnaire: [Eurobarometer 90.2 Basic Bilingual Questionnaire](https://dbk.gesis.org/dbksearch/download.asp?id=65967)
* Citation: [ZA7488 Bibtex](https://search.gesis.org/ajax/bibtex.php?type=research_data&docid=ZA7488&lang=en)

`QB5 To what extent do you agree or disagree with each of the following statements? - Fighting climate change and using energy	more efficiently can boost the economy	and	jobs in	the	EU` (agreement-disagreement 4-scale)

`QB5 To what extent do you agree or disagree with each of the following statements? - Promoting	EU expertise in new clean technologies to countries outside	the	EU	can	benefit	the	 EU	economically`	(agreement-disagreement 4-scale)

`QB5 To what extent do you agree or disagree with each of the following statements? - Reducing fossil fuel imports from outside the	EU	can	benefit the	EU economically` (agreement-disagreement 4-scale)

`QB5 To what extent do you agree or disagree with each of the following statements? - Reducing fossil fuel imports from outside	the	EU	can	increase the security of EU energy supplies` (agreement-disagreement 4-scale)

`QB5 To what extent do you agree or disagree with each of the following statements? - More	public	financial	support	should	be	given	to	the	transition to	clean	energies even if it means	subsidies	to	fossil fuels should	be reduced.` (agreement-disagreement 4-scale)


## Eurobarometer 91.3 (2019)

European Commission, Brussels; Directorate General Communication, COMM.A.3 ‘Media Monitoring and Eurobarometer’
GESIS Data Archive, Cologne. ZA7572 Data file Version 1.0.0, https://doi.org/10.4232/1.13372

* Data file: [ZA7572](https://dbk.gesis.org/dbksearch/sdesc2.asp?db=e&no=7572) data file [@ZA7572].
* Questionnaire: [Eurobarometer 91.3 Basic Bilingual Questionnaire](https://dbk.gesis.org/dbksearch/download.asp?id=66774)
* Citation: [ZA7572 Bibtex](https://search.gesis.org/ajax/bibtex.php?type=research_data&docid=ZA7572&lang=en)


`QB4 To what extent do you agree or disagree with each of the following statements? - Taking action on climate change will lead to innovation that will make EU companies more competitive (N)` (agreement-disagreement 4-scale)

`QB4 To what extent do you agree or disagree with each of the following statements? - Promoting	EU	expertise	in	new	clean	technologies	to countries	outside	the	EU	can	benefit	the	 EU	economically`	(agreement-disagreement 4-scale)

`QB4 To what extent do you agree or disagree with each of the following statements? - Reducing	fossil	fuel	imports	from	outside	the	EU	can	benefit the	EU	economically` (agreement-disagreement 4-scale)

`QB4 To what extent do you agree or disagree with each of the following statements? - Adapting to the adverse impacts of climate change can have positive outcomes for citizens in the EU` (agreement-disagreement 4-scale)

`QB5 Have	you	personally taken	any	action to fight	climate	change	over the past six	months?` (binary)

## References